### ISSUE TITLE
AC group meetings

### ISSUE THREAD

**Issue by ramorrismorris** [tdwg/ac#102]
See  #97 wherein @danstoner
@baskaufs may already have something in mind or  tdwg itself may. If not, here's a useful simple model.

1.  Provide a google calendar.
2.  For any scheduled meeting add a calendar entry.
3.  Fix a single fixed google doc in which agenda and notes are kept.

**Comment by baskaufs** [comment]
Thanks, Bob.  There is a Audubon Core Maintenance Group google calendar and I think the core members have already been invited to share it.  If anyone else wants to be invited to the calendar, let me know and I'll add you.  I have just created an entry for the 2018-06-13 meeting at 18:00 UTC.  I believe that it should automatically adjust for your default local time zone.  

I have created the start of a meeting notes Google Doc.  There is a link to a version of it with editing enabled, so anyone in the calendar should be able to edit.  I also copied the same Hangout link that we used last time to that calendar entry.  Closer to the meeting, I'll create a viewable, but non-editable version that I'll link from the Issue Tracker issue that I use to publicly announce the meeting.  So I think we should be set on this.
