### ISSUE TITLE
Create best practice document based on exemplary implementations

### ISSUE THREAD

**Issue by nielsklazenga** [tdwg/ac#117]
Find out how GBIF, iDigBio, SYMBIOTA etc. are, or would like to, be using Audubon Core and create best practice document based on that.

**Comment by chicoreus** [comment]
An example of use is the NEVP project, wrapping DwC and AC assertions about information captured at a high throughput digitization apparatus in a W3C Annotation document for transport to Symbiota and the database of record for ingest of that data.  For an example document see: https://sourceforge.net/p/filteredpush/svn/HEAD/tree/FP-Design/trunk/ontologies/oadExamples/NEVP_specimen_example.xml  There is also code in Symbiota to process these documents.   @ramorrismorris was involved in crafting these documents.

**Comment by baskaufs** [comment]
This issue duplicates the older issue https://github.com/tdwg/ac/issues/63, so the comments have been transferred to it and I'm closing this one.
