### ISSUE TITLE
Create controlled vocabularies for ac:subjectPart and ac:subjectOrientation

### ISSUE THREAD

**Issue by nielsklazenga** [tdwg/ac#118]
Matt Blisset indicated that GBIF could make use of the subjectPart and subjectOrientation fields.

**Comment by baskaufs** [comment]
This issue resulted in the creation of the [Views Controlled Vocabularies Task Group](https://github.com/tdwg/ac/tree/master/views), which is active. There is therefore no reason to maintain this as an issue.
