### ISSUE TITLE
Update AC satellite website

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/ac#120]
Todo:

- [x] Define navbar
- [x] Choose directories or files for guides
- [x] Setup homepage (e.g. introduction.md)
- [ ] Use definition lists for guide metadata
- [x] Check links to images
- [x] Decide if site should _also_ live at http://rs.tdwg.org/ac or rather new https://ac.tdwg.org/

Pages that should return something:

- [x] http://rs.tdwg.org/ac/introduction/
- [x] http://rs.tdwg.org/ac/guide/
- [x] http://rs.tdwg.org/ac/ (currently empty)
- [x] http://rs.tdwg.org/ac/structure/
- [x] http://rs.tdwg.org/ac/termlist/

(Markdown) files that can be removed:

- [ ] 404.html
- [ ] about.md
- [ ] posts/2018-08-13-welcome-to-jekyll.markdown

**Comment by peterdesmet** [comment]
@baskaufs @nielsklazenga: some feedback required for the new AC website:

1. It’s a bit odd to have a homepage (currently blank) and an introduction page. Should the introduction page disappear and become the homepage?
2. Do you want terms/ or termlist/ for the terms?
3. Is the order in the navbar ok?
4. Do you want to maintain files guide.md (current setup) or directories guide/index.md (dwc setup). Both work equally fine: first one is jekyll like, second one allows to organize related files.

**Comment by nielsklazenga** [comment]
@peterdesmet I had it as 'home/' (index.md) and 'terms/' (terms.md), but @baskaufs wanted to keep the old names. I think it's mainly a matter of keeping existing urls alive. I would like it to be consistent with what other standards, e.g. Darwin Core, do.

Order of the nav. bar is fine.

Also for the choice between files or directories, I'd like to follow whatever you decide to do for Darwin Core.

**Comment by nielsklazenga** [comment]
@peterdesmet Look at all the URLs in https://tdwg.github.io/ac/termlist/. They are from the original standard and I think should be kept alive. If they could be redirected to the current pages, I think we can use the URLs that make sense now for these pages.

**Comment by baskaufs** [comment]
IRI dereferencing documents in the http://rs.tdwg.org/ is now working and the IRIs given in the header sections of those documents now actually dereference to those documents. The some of the IRIs given in the todo section above are wrong, but the right ones work.

**Comment by baskaufs** [comment]
I am checking the box for "Decide if site should also live at http://rs.tdwg.org/ac or rather new https://ac.tdwg.org/". It cannot live at http://rs.tdwg.org/ac because that IRI denotes the Audubon Core vocabulary itself dereferences to the technical metadata about the vocabulary. I'm not sure how much it matters where the "site" lives. The two things that matter are whether the permanent IRIs for the documents dereference somewhere (they do) and that we have some place to archive AC records (we do: it's the GitHub repo for AC). The important thing is that both of this things are linked to the Audubon Core landing page (https://www.tdwg.org/standards/ac/, and they are). So I think this is a moot point.

**Comment by baskaufs** [comment]
Similarly, I'm not sure that "Choose directories or files for guides" is important. Any citation of the guides should be their permanent IRIs, not the page to which they are redirected. Given that outlook, I'm not sure that there is any reason why they can't just have the URLs that they have.

**Comment by baskaufs** [comment]
@peterdesmet With regards to "Setup homepage (e.g. introduction.md)", can we just set "Home" in the navbar to link to the Audubon Core landing page: https://www.tdwg.org/standards/ac/ ?

**Comment by baskaufs** [comment]
@peterdesmet I don't know about the three Markdown documents to be removed. I don't see them anywhere in the docs folder where the website lists. The remaining checkboxes "Define navbar" and "Use definition lists for guide metadata" are technical things I don't understand. It seems like the only real thing here that needs to be done is to make the "Home" link on the Navbar point to the AC landing page. If we do that, can we close this issue?

**Comment by MattBlissett** [comment]
I missed this comment in September:

> I'm not sure how much it matters where the "site" lives. The two things that matter are whether the permanent IRIs for the documents dereference somewhere (they do) and that we have some place to archive AC records (we do: it's the GitHub repo for AC). The important thing is that both of this things are linked to the Audubon Core landing page (https://www.tdwg.org/standards/ac/, and they are). So I think this is a moot point.

The point of using https://ac.tdwg.org/ or similar rather than https://tdwg.github.io/ac/ is to allow for an easier migration if we should decide to stop using GitHub – we have full control of the former, and control only as far as GitHub allow for the latter.

**Comment by baskaufs** [comment]
If people have actually linked to the rs.tdwg.org permanent doc URLs, we could move to the ac.tdwg.org subdomain without breaking anything; it would just require changing the redirect URLs. I think most of the links within the website are relative, so they would be fine. The question is how many other places link to the existing tdwg.github.io/ac/ paths. I suppose we could search out the ones in TDWG sites and change them, but I don't know how many other places will end up with broken links.

I guess my inclination would be to leave things as they are. If we move from GitHub in the future, there will be exactly the same number of broken links as there would be if we changed to ac.tdwg.org now. So I can't think of an advantage of switching now. 

When we set up the website, I didn't know that the tdwg.org subdomain was an option. We should make sure that any new standards websites don't make the same mistake.

**Comment by nielsklazenga** [comment]
Hi @baskaufs , changing to https://ac.tdwg.org will not break the https://tdwg.github.io/ac paths. As long as the site is in GitHub, those paths will always be there. Try, for example, http://tdwg.github.io/dwc/terms.

So, if we change now, there will be no broken links, but, if we wait until we move the site from GitHub, there will be. I have the AVH website in the Azure CDN, which sets me back about $2 AU per year, so the cost is not really a factor. The site is still managed in GitHub. However, if I ever want to use anything else than Jekyll to create the site, GitHub is not the best option for the site anymore. The TDWG website itself is maintained, but not hosted (I think) in GitHub.

We did not make a mistake. Sites in development always have different URLs from sites in production.

**Comment by baskaufs** [comment]
Alright, that makes sense @nielsklazenga. I wasn't thinking about that. @MattBlissett do you control the mapping of the tdwg.org domain? Can you map ac.tdwg.org to https://tdwg.github.io/ac/ ? If so, I don't see any reason not to switch over and start changing any links.

**Comment by MattBlissett** [comment]
I've set up the DNS for ac.tdwg.org, but I don't have admin access on this repository.  Could you go to Settings->Pages https://github.com/tdwg/ac/settings/pages and set the custom domain to ac.tdwg.org, and tick "Enforce HTTPS" too.

(Alternatively, add me as an administrator to the repository.)

**Comment by baskaufs** [comment]
@MattBlissett I have made the setting change. It seems to be working now, except that I get a big ugly warning screen from my browser and the error message:

>Websites prove their identity via certificates. Firefox does not trust this site because it uses a certificate that is not valid for ac.tdwg.org. The certificate is only valid for the following names: www.github.com, *.github.com, github.com, *.github.io, github.io, *.githubusercontent.com, githubusercontent.com

That may go away because it said there might be a delay of up to a day for the certificate to work its way through the system. I'll try again tomorrow to see if it's gone away then.

I also tried to add you as a member of the AC team, but it says "this person is not a member of this organization". I'm unclear about what that means. However, I had no problem adding you as an individual with admin access. So I suppose that's good enough, although not clean. @stanblum or another site admin may know how to fix this.

**Comment by MattBlissett** [comment]
https://ac.tdwg.org/ works fine for me (no warning), so I think it was just a short delay.

I don't seem to be an admin on this repository, but it doesn't matter. The setup is fine.

**Comment by baskaufs** [comment]
I don't see the warning any more, so I think we are good to go. Thanks, @MattBlissett !

**Comment by MattBlissett** [comment]
And you did invite me correctly, the email from GitHub had gone to my personal address.

**Comment by baskaufs** [comment]
Although I don't see that every item in the list of the first comment have been completed, I don't actually know what needs to be done with respect to them. If they are a burning issue for anyone, they can re-open this issue, or better yet, open a different issue the addresses the specific problem to be solved.
