### ISSUE TITLE
Change build script for term list to pick up styles from TDWG Jekyll template

### ISSUE THREAD

**Issue by nielsklazenga** [tdwg/ac#122]
See what @peterdesmet did with Darwin Core: https://dwc.tdwg.org/terms/. We don't have to adopt everything, but can discuss what to adopt and what not.

**Comment by baskaufs** [comment]
One possible issue is the term list document's status as a part of the standard.  In the case of the DwC quick reference guide, it was decided that it was not included within the standard and could therefore be changed or re-designed at will.  So this is an issue we'll have to consider.

**Comment by nielsklazenga** [comment]
When I looked again at the AC term list this morning, I actually thought it looks pretty good. I am really just thinking about applying the styles to the tables, so that they don't look as massive. And I'm talking only design, not layout.

**Comment by baskaufs** [comment]
Oh, that would probably be great.  If it's just a styling thing, I'm sure we can do whatever we want.

**Comment by nielsklazenga** [comment]
Thought so. I just put in the GitHub issue, as I don't have time to do it right now.

**Comment by baskaufs** [comment]
We may work on this later but for now am closing
