### ISSUE TITLE
Unfreeze or update borrowed DwC term versions to bring in updated definitions

### ISSUE THREAD

**Issue by baskaufs** [tdwg/ac#134]
The notes in Section 7.5 of the Audubon Core [Term List document](https://tdwg.github.io/ac/termlist/) state that the borrowed Darwin Core geography terms are specifically the versions from 2009-12-09. 

Since that time, there has been a significant change in the documentation of Darwin Core terms.  Terms whose definitions previously had a statement beginning with "Best practice is to use a controlled vocabulary..." now have that best practice statement removed from the term definition and placed into the non-normative comments field.  

This type of change is in keeping with the metadata clean up that we are trying to accomplish with the Audubon Core term metadata (e.g. moving inappropriately placed text among the term definitions, usage guidelines, and notes; see Issue #115) .  However, by having the DwC term versions frozen at 2009-12-09, AC isn't getting the cleaner (current) definitions.  

I can see the rationale for having frozen versions when a TDWG vocabulary borrows from another vocabulary outside of TDWG.  We don't necessarily want others changing definitions that we've adopted out from under us.  However, I think the situation is different when we borrow from a vocabulary within TDWG.  In theory, the TAG would be on the lookout for situations where term changes would have adverse effects on interoperability across vocabularies.  So allowing borrowed TDWG terms to "float" with the current versions seems safer to me.  In this case, solving text misplaced in the wrong fields in DwC would have simultaneously solved the problem for Audubon Core - something that didn't happen since the AC versions are fixed.

At a minimum, I would recommend doing a one-time update refreezing the borrowed DwC terms at the current versions.  But it might be better to just let them float.  

Thoughts @tdwg/tag-fs ?

**Comment by baskaufs** [comment]
See also Issue #100 regarding a more recent version of the IPTC vocabulary

**Comment by hlapp** [comment]
> The notes in Section 7.5 of the Audubon Core [Term List document](https://tdwg.github.io/ac/termlist/) state that the borrowed Darwin Core geography terms are specifically the versions from 2009-12-09.

The actual text states in fact this:
> All geography terms from the Darwin Core version of 9 Dec 2009 are deemed included in the Core Layer. 

Indeed this _could_ be read in the way you paraphrased it, but it could also be read as _all geography terms present in that DwC version, in whatever their current definition is_. My reading would in fact be the latter; i.e., I don't see anything in the document that says _but not including any updates that may have been made to these terms after Dec 9, 2009_. So I'm not sure there's a problem unless there are DwC geography terms now that weren't there in Dec 2009, or that have been removed since. It seems this is not the case?

**Comment by baskaufs** [comment]
I see your point @hlapp.  Our current goal is to make the documentation as clear as possible, so we need to change to text to be unambiguous.  The person who would know the original intent of the text would be @ramorrismorris, although what we probably really need to do is to have a decision about whether it's generally a better practice to freeze the versions or let them float.  We could change the text to clarify in either way.

**Comment by baskaufs** [comment]
I should also note that the original documentation did not list the terms to be included - it simply included them by reference.  We updated the documentation to list them explicitly in order to relieve the burden of users having to look them up.  Given the current approach of explicit listing, the statement would be unnecessary if the correct interpretation of it is that it defines the terms (not versions) to be included.

**Comment by baskaufs** [comment]
The term list document was clarified by removing the text about the DwC terms to be included, since they are now enumerated.  We now have a [policy](https://github.com/tdwg/ac/blob/master/policies.md#21-versioning-of-terms-borrowed-from-other-vocabularies) stating that we will automatically update other borrowed TDWG terms when they are updated in their "home" vocabularies.  However, there is some lack of clarity about the current versioning of DwC terms, so this was not addressed in the 2020-01-27 version of Audubon Core. This aspect still needs to be addressed.

**Comment by baskaufs** [comment]
This was addressed by https://github.com/tdwg/rs.tdwg.org/pull/46 and https://github.com/tdwg/ac/commit/e7b4fe4d5f2182b39f4813faf3cd38fc551b5970
