### ISSUE TITLE
Audubon Core Maintenance Group call August 29 21:00 UTC

### ISSUE THREAD

**Issue by baskaufs** [tdwg/ac#136]
The Audubon Core Maintenance Group will have an online meeting at 21:00 UTC on August 29.  That corresponds to 5:00 PM Eastern (US) daylight time Thursday Aug 29, 11:00 PM Central European Summer Time Thursday Aug 29, and 7:00 AM Australian Eastern Standard time Friday Aug 30.

The main topic of this meeting will be to review the proposed term metadata changes of Issues #130, #131, and #132.  Please review the proposed changes and comment on the Google Doc 
https://docs.google.com/document/d/12Ck4t_x9LtG0BgPuBcNNqtYppNCP_Rj5F7bdgkmFvGY/edit?usp=sharing
prior to the meeting.  At the meeting we will try to determine which of the proposed changes can be implemented, and which need additional review.

I'll post a meeting link nearer to the time of the meeting.

**Comment by nielsklazenga** [comment]
Thanks @baskaufs  I found some things that I hadn't noticed before. I have very little to add to your suggestions though (just agreement).

Don't forget to share the meeting link.

**Comment by baskaufs** [comment]
The notes for the 2019-08-29 AC Maintenance Group call are [here](https://github.com/tdwg/ac/blob/master/historical/2019-08-29-meeting-notes.pdf).  Decisions are in red following the agenda items.
