### ISSUE TITLE
Audubon Core Maintenance Group call 21:00 2019-09-26 UTC

### ISSUE THREAD

**Issue by baskaufs** [tdwg/ac#140]
The Audubon Core Maintenance Group will have an online meeting at 21:00 UTC on September 26. That corresponds to 5:00 PM Eastern (US) daylight time Thursday Sep 26, 11:00 PM Central European Summer Time Thursday Sep 26, and 7:00 AM Australian Eastern Standard time Friday Sep 27.

The purpose of the meeting is to follow up on the action items from the previous meeting and plan for the upcoming TDWG annual meeting.

**Comment by nielsklazenga** [comment]
RBG Victoria is inviting you to a scheduled Zoom meeting.

Topic: TDWG Audubon Core Maintenance Group
Time: Sep 27, 2019 07:00 AM Canberra, Melbourne, Sydney

Join Zoom Meeting
https://zoom.us/j/601407817

One tap mobile
+17207072699,,601407817# US (Denver)
+16465588656,,601407817# US (New York)

Dial by your location
        +1 720 707 2699 US (Denver)
        +1 646 558 8656 US (New York)
Meeting ID: 601 407 817
Find your local number: https://zoom.us/u/au5burZHe

**Comment by baskaufs** [comment]
Don't forget the upcoming Audubon Core Maintenance Group meeting Thursday, Sep 26 at 21:00 UTC.  Check [this issue]https://github.com/tdwg/ac/issues/140) for times in various time zones and for connection information.

Topics to be discussed will be a report on progress on the documentation cleanup, task group reports, our annual report to the Executive, and application of RFC 2119 to our documents.

**Comment by baskaufs** [comment]
The [notes from the 2019-09-26 Maintenance Group call](https://github.com/tdwg/ac/blob/master/historical/2019-09-26-meeting-notes.pdf) have been posted.
