### ISSUE TITLE
Broken derivedFrom links

### ISSUE THREAD

**Issue by cgendreau** [tdwg/ac#141]
Some `derivedFrom` links on https://terms.tdwg.org/wiki/Audubon_Core_Term_List are not resolving. For example in https://terms.tdwg.org/wiki/Audubon_Core_Term_List#dc:source .

I think they should simply be `ac:derivedFrom` .

I can send a PR but since `termlist.md` is generated, what is the source that `build_page` is using the retrieve the vocabulary?

**Comment by baskaufs** [comment]
Maybe at the TDWG meeting we should ask around about the status of the terms.tdwg.org URLs/wiki.  My impression was that at some point it had some kind of official status, but nobody seems interested in maintaining it now.  I would just prefer to get rid of it, or at least clearly mark the pages as out of date.

**Comment by baskaufs** [comment]
I'm going to close this issue since I opened a more specific one to deal with the problem #142

**Comment by cgendreau** [comment]
Sounds good. Thanks @baskaufs.
