### ISSUE TITLE
Try to get rid of outdated terms.tdwg.org wiki pages and fix term dereferencing

### ISSUE THREAD

**Issue by baskaufs** [tdwg/ac#142]
Let's try to get clarification about this at or before the TDWG 2019 annual meeting.

**Comment by MattBlissett** [comment]
I've just been confused by the multiple places it's possible to read the AC standard, or an old version of it.

Was there any clarification at the meeting?

We have https://tdwg.github.io/ac/, http://rs.tdwg.org/ac/ (both with empty homepages, but the former linked to from https://www.tdwg.org/standards/ac/), https://terms.tdwg.org/wiki/Audubon_Core, https://github.com/tdwg/ac (with a link back to the same page), and mention of https://ac.tdwg.org/

For longevity, and to give TDWG control of any necessary future migration, I suggest avoiding Github domains — we can set up redirects, even if it involves ugly hacking, on terms.tdwg.org, but we can't for tdwg.github.io.

I managed the DNS for tdwg.org, but I don't manage the Wiki, so I don't know what could be done about that.

**Comment by baskaufs** [comment]
This has been resolved with https://github.com/tdwg/tag/issues/26 and https://github.com/tdwg/rs.tdwg.org/issues/36
