### ISSUE TITLE
Audubon Core Maintenance Group call 21:00 UTC, Thursday, Jan. 30

### ISSUE THREAD

**Issue by baskaufs** [tdwg/ac#152]
The Audubon Core Maintenance Group will have an online meeting at 21:00 UTC Thursday, 2020-01-30.  That corresponds to 4:00 PM Thursday, Eastern (US) Standard Time (New York), 9:00 PM Thursday, GMT (London), 10:00 PM Central European Time (Stockholm), and 8:00 AM Friday Australian Eastern Daylight Time (Canberra).

At the meeting I'll report briefly on the release of the new Audubon Core version and we will devote the rest of the meeting to discussing how to move forward on developing new terms and a best practice guide for sounds.

**Comment by nielsklazenga** [comment]
RBG Victoria is inviting you to a scheduled Zoom meeting.

Topic: Audubon Core Maintenance Group meeting
Time: Jan 30, 2020 09:00 PM London

Join Zoom Meeting
https://zoom.us/j/177975267

Meeting ID: 177 975 267

One tap mobile
+16699009128,,177975267# US (San Jose)
+16465588656,,177975267# US (New York)

Dial by your location
        +1 669 900 9128 US (San Jose)
        +1 646 558 8656 US (New York)
Meeting ID: 177 975 267
Find your local number: https://zoom.us/u/au5burZHe

**Comment by baskaufs** [comment]
Just a reminder that the Audubon Core online meeting is in a little over four hours. See [this issue](https://github.com/tdwg/ac/issues/152) for details on the time and participating in the call.

The main topic of the call will be adding terms related to sound.

**Comment by baskaufs** [comment]
The notes from the 2020-01-30 call have been posted [here](https://github.com/tdwg/ac/blob/master/historical/2020-01-30-meeting-notes.pdf)
