### ISSUE TITLE
Biocomplexity Thesaurus no longer available (Iptc4xmpExt:CVterm)

### ISSUE THREAD

**Issue by baskaufs** [tdwg/ac#154]
The Biocomplexity Thesaurus, a source of recommended values for Iptc4xmpExt:CVterm, appears to no longer be online. The URL given in the Audubon Core documentation for the term, https://www2.usgs.gov/core_science_systems/csas/biocomplexity_thesaurus/, does not dereference to the thesaurus.  A search at usgs.gov returns results: https://www.usgs.gov/science-explorer-results?es=biocomplexity+thesaurus but the link does not lead to the thesaururs.  The Internet Archive has scanned the landing page https://web.archive.org/web/20170208161320/https://www2.usgs.gov/core_science_systems/csas/biocomplexity_thesaurus/search_thesaurus.html but since it appears to query a database that's not in the Internet Archive, the landing page is useless.  

If we cannot locate an archived copy of the thesaurus to link in the notes, we should remove it from the list of recommended controlled vocabularies.

**Comment by MattBlissett** [comment]
https://www1.usgs.gov/csas/biocomplexity_thesaurus/ maybe? Linked from https://www2.usgs.gov/science/cite-view.php?cite=1339

**Comment by baskaufs** [comment]
OK, false alarm. Closing this.
