### ISSUE TITLE
View for "in habitat"

### ISSUE THREAD

**Issue by baskaufs** [tdwg/ac#166]
Boyce Tankersley (and others) have suggested including a view of the specimen/organism in its habitat at the full organism scale. "Helps us to return to the same specimen locale, if needed.  Important for DNA, seed, vegetative propagation, herbarium voucher, image, etc. recollections."

**Comment by edwbaker** [comment]
I would also add "habitat" - I can think of a few instances where I have useful habitat photos but the organism itself is not visible (small cryptic insects; collections of mosquito larvae).

**Comment by edwbaker** [comment]
It would also be worth getting some palaeo community input. I'm thinking along the lines of in-situ photographs of fossils, photographs showing the relevant stratigraphy, etc.
