### ISSUE TITLE
Proposal for controlled vocabulary for ac:variant and ac:variantLiteral

### ISSUE THREAD

**Issue by baskaufs** [tdwg/ac#170]
The Notes for [ac:variant](http://rs.tdwg.org/ac/terms/variant) and [ac:variantLiteral](http://rs.tdwg.org/ac/terms/variantLiteral) suggest values to be used with those properties. This proposal will replace those Notes with Usage guidelines specifying that those terms should use values from a controlled vocabulary that is also introduced with this proposal. 

**Term changes:**

`ac:variant`: 

- Change Definition to: "The category describing this Service Access Point variant, denoted by an IRI."
- Delete Notes
- Add Usage: "Values SHOULD be selected from the Controlled Vocabulary for Audubon Core variant. In text-based systems such as tables, IRI values MUST be in unabbreviated form."

Note: The current unofficial recommended URIs are at odds with effective management of the `ac:` namespace and the local names are inconsistent with evolving TDWG practice. GBIF reports that very few providers are supplying these unofficial URIs and there would be little disruption if they were changed.

`ac:variantLiteral`:

- Change Definition to: "The category describing this Service Access Point variant, denoted by a controlled value string."
- Delete Notes
- Add Usage: "Values SHOULD be selected from the Controlled Vocabulary for Audubon Core variant. It is best practice to use ac:variant instead of ac:variantLiteral whenever practical."

Notes: The description of the variant types is included in the controlled vocabulary - a better place to maintain that information than in the term Notes. To maintain stability, the previously suggested controlled values for `ac:variantLiteral` have not been changed. 

**Proposed controlled vocabulary**

A draft of the proposed controlled vocabulary is [here](https://github.com/tdwg/rs.tdwg.org/blob/variant_cv/process/page_build_scripts/variant.md). Metadata for the controlled vocabulary terms is summarized in [this CSV table](https://github.com/tdwg/rs.tdwg.org/blob/variant_cv/acvariant/acvariant.csv).

This proposal creates a new vocabulary within the Audubon Core standard. According to the [IRI patterns used in the `http://rs.tdwg.org/` subdomain](https://github.com/tdwg/rs.tdwg.org/blob/master/README.md#21-patterns-for-current-resources-in-the-standards-hierarchy), the first level IRI path segment must differ from that of the main Audubon Core vocabulary (`http://rs.tdwg.org/ac/`). The proposed first level IRI path segment for this vocabulary is `acvariant`, making the IRI for the vocabulary `http://rs.tdwg.org/acvariant/`. The proposed namespace IRI for terms in the vocabulary is `http://rs.tdwg.org/acvariant/values/`. The proposed preferred namespace abbreviation matches the first level IRI path segment: `acvariant:`.

In accordance with Section 4.1.2 of the [Standards Documentation Specification](http://rs.tdwg.org/sds/doc/specification/), the class of all controlled value terms is `skos:Concept`. Following typical SKOS practice, the concepts are also grouped into a concept scheme.

**Comment by danstowell** [comment]
I do concur with the idea discussed 2020-07-22, to add "visualization" as a term, and perhaps also "sonogram" which would be a sub-category of it. The motivation being that sonograms (spectrograms) are often presented in audio archives, fulfilling a similar role as a thumbnail.

**Comment by edwbaker** [comment]
I would also add oscillogram - from a collection management point of view there are quite a number of physical oscillograms within the NHM collection, many of which are also scanned and on BioAcoustica.

We also have scans of the original metadata sheets for each recording - not sure if that's something we could fit into here?

**Comment by baskaufs** [comment]
Is there a label for this kind of thing that would be generic enough to cover all of the kinds of things we discussed where there is a visual representation of a sound recording?  I think that would be preferable to having several separate items like "sonogram" and "oscillogram".  "visualization" is a possibility, although I would prefer some other term if we could think of one. There are two reasons: visualization can broadly mean a lot of things beyond what we are talking about here, and it would be good to have a controlled value string for the term that doesn't have different British and American English spellings.

**Comment by edwbaker** [comment]
visual/graphic representation?

or just "visual"?

**Comment by baskaufs** [comment]
I think "visual" might be good. We would want to clarify in the definition, but I think that would connote generally a visual representation of something that isn't normally represented as a still image.

**Comment by baskaufs** [comment]
New version of list of terms document is [here](https://github.com/tdwg/rs.tdwg.org/blob/variant_cv/process/page_build_scripts/variant.md)

**Comment by baskaufs** [comment]
Approved in [Executive decision 30](http://rs.tdwg.org/decisions/decision-2020-10-13_30). Incorporated in [rs.tdwg.org release 2020-10-13](https://github.com/tdwg/rs.tdwg.org/releases/tag/2020-10-13).
