### ISSUE TITLE
Proposal for controlled vocabulary for Dublin Core format

### ISSUE THREAD

**Issue by baskaufs** [tdwg/ac#171]
The Notes for [dc:format](https://tdwg.github.io/ac/termlist/#dc_format) suggest values to be used with that property. The Usage for [dcterms:format](https://tdwg.github.io/ac/termlist/#dcterms_format) indicates that a URI should be used as a value for the property, but does not suggest any source for URIs. This proposal will replace this guidance with Usage guidelines specifying that those terms should use values from a controlled vocabulary that is also introduced with this proposal. 

**Term changes:**

`dc:format`: 

- Change Usage to: "A controlled value string describing the technical format of the resource (file format or physical medium). The string SHOULD be a controlled value from the the Audubon Core Controlled Vocabulary for Dublin Core format, although it MAY be any Media Type (MIME type) value from the IANA list of Media Types (https://www.iana.org/assignments/media-types/media-types.xhtml) or any commonly used file extension string.
- Change Notes to: "This term can be used to describe offline digital content. In cases where the provided Service Access Point URL includes a standard file extension from which the format can be inferred, it is permissible to not provide a value for this property. See also the entry for dcterms:format in the Audubon Core term list document and see the DCMI FAQ on DC and DCTERMS Namespaces, https://web.archive.org/web/20171126043657/https://github.com/dcmi/repository/blob/master/mediawiki_wiki/FAQ/DC_and_DCTERMS_Namespaces.md, for discussion of the rationale for terms in two namespaces.  It is best practice to use dcterms:format instead of dc:format whenever practical. Normal practice is to use the same Label if both are provided. Labels have no effect on information discovery and are only suggestions."

`dcterms:format`:

- Change Usage to: "An IRI denoting the technical format of the resource (file format or physical medium). The IRI SHOULD be from the Audubon Core Controlled Vocabulary for Dublin Core format.
- Change Notes to: "In cases where an IRI for the format does not exist in the controlled vocabulary, a provider can omit this property and provide a media type or file extension value for dc:format. See the DCMI FAQ on DC and DCTERMS Namespaces, https://web.archive.org/web/20171126043657/https://github.com/dcmi/repository/blob/master/mediawiki_wiki/FAQ/DC_and_DCTERMS_Namespaces.md, for discussion of the rationale for terms in two namespaces. Normal practice is to use the same Label if both are provided. Labels have no effect on information discovery and are only suggestions."

**Proposed controlled vocabulary**

A draft of the proposed controlled vocabulary is [here](https://github.com/tdwg/rs.tdwg.org/blob/format_cv/process/format.md). Metadata for the controlled vocabulary terms is summarized in [this CSV table](https://github.com/tdwg/rs.tdwg.org/blob/format_cv/format/format.csv).

This proposal creates a new vocabulary within the Audubon Core standard. According to the [IRI patterns used in the `http://rs.tdwg.org/` subdomain](https://github.com/tdwg/rs.tdwg.org/blob/master/README.md#21-patterns-for-current-resources-in-the-standards-hierarchy), the first level IRI path segment must differ from that of the main Audubon Core vocabulary (`http://rs.tdwg.org/ac/`). The proposed first level IRI path segment for this vocabulary is `format`, making the IRI for the vocabulary `http://rs.tdwg.org/format/`. Note: the path segment `format` was used rather than `acformat` since this controlled vocabulary may be used for TDWG standards other than Audubon Core. The proposed namespace IRI for terms in the vocabulary is `http://rs.tdwg.org/format/values/`. The proposed preferred namespace abbreviation is `acformat:`. Note: this abbreviation is not simply `format:` since that namespace abbreviation is likely to be in use elsewhere.

In accordance with Section 4.1.2 of the [Standards Documentation Specification](http://rs.tdwg.org/sds/doc/specification/), the class of all controlled value terms is `skos:Concept`. Following typical SKOS practice, the concepts are also grouped into concept schemes. For a rationale for separating the concepts into two concept schemes, see [sections 2.2 and 2.3](https://github.com/tdwg/rs.tdwg.org/blob/format_cv/process/format.md#22-relationship-between-concepts-and-concept-schemes) in the draft list of terms.

**Comment by edwbaker** [comment]
Some additional physical media types to consider (based on holdings at NHM London):

- Analogue Audio Tape (e.g. reel-to-reel)
- Audio Cassette
- Digital Audio Tape (DAT standard)
- MiniDisc
- Records (Vinyl)

Some of these have a variety of "settings" e.g. tape speed for reel-to-reel tapes that might be of importance to include at some point.

**Comment by edwbaker** [comment]
Mixed-CD is also a potential option to consider - these have both data (generally as a hidden first track) and audio tracks

**Comment by baskaufs** [comment]
Great! I've added them to the list and they will show up in the next draft.

**Comment by baskaufs** [comment]
I forgot to hack the page build script to include the `skos:exactMatch` relationships that were expressed in the [CSV metadata table](https://github.com/tdwg/rs.tdwg.org/blob/format_cv/format/format.csv). I have fixed that in https://github.com/tdwg/rs.tdwg.org/commit/adecbac8fbaa8f98185f3acb1d3cef1c0e8d8569, so the [list of terms document](https://github.com/tdwg/rs.tdwg.org/blob/format_cv/process/format.md) now correctly links the file extension concepts in the [list of terms](https://github.com/tdwg/rs.tdwg.org/blob/format_cv/process/format.md) document to the media types and physical media concepts.

**Comment by baskaufs** [comment]
Approved in [Executive decision 29](http://rs.tdwg.org/decisions/decision-2020-10-13_29). Incorporated in [rs.tdwg.org release 2020-10-13](https://github.com/tdwg/rs.tdwg.org/releases/tag/2020-10-13).
