### ISSUE TITLE
Proposal to add new terms ac:freqLow and ac:freqHigh

### ISSUE THREAD

**Issue by danstowell** [tdwg/ac#178]
Term Name: ac:freqLow
Term Name: ac:freqHigh

Type: rdf:Property

Label: Lower frequency bound
Label: Upper frequency bound

Required: No

Repeatable: No

Definition: The lowest frequency of the phenomena reflected in the multimedia item.
Definition: The highest frequency of the phenomena reflected in the multimedia item.

Usage: Numeric value in hertz (Hz)

Notes: These terms refer to the sound events depicted and not to the constraints of the recording medium, so are in principle independent from sampleRate. If dwc:scientificName is specified, these frequency bounds refer to the sounds of the species given in the dwc:scientificName throughout the whole recording. Although many users will specify both freqLow and freqHigh, it is permitted to specify just one or the other, for example if only one of the bounds is discernible.

Justification for the term addition: “Time-frequency boxes” are a common approach for labelling events within bioacoustic sound recordings. Audio recordings can be used to explore and validate taxon identity for insect sounds. For many insect sounds (e.g. extended calling or chorusing), frequency bounds can be much clearer than time bounds. Thus, in a soundscape recording, it can be desirable to associate a taxon label with some sub-region of the audio, but as frequency bounds without time bounds. In search queries, it can often be desirable to target (or exclude) animal sounds that occur within specific frequency ranges.

Proposed by myself and @edwbaker

**Comment by baskaufs** [comment]
Minor correction changing `rdfs:Property` to `rdf:Property`

**Comment by baskaufs** [comment]
Corrected capitalization of "hertz"

**Comment by baskaufs** [comment]
Approved in [Executive decision 32](http://rs.tdwg.org/decisions/decision-2020-10-13_32). Incorporated in [rs.tdwg.org release 2020-10-13](https://github.com/tdwg/rs.tdwg.org/releases/tag/2020-10-13).
