### ISSUE TITLE
Update ac:resourceCreationTechnique if an explicit "sample rate" term is added

### ISSUE THREAD

**Issue by danstowell** [tdwg/ac#179]
If we import term mo:sample_rate (#177) or something similar, we should then remove the phrase "audio sampling rate" from the notes for [ac:resourceCreationTechnique](http://rs.tdwg.org/ac/terms/resourceCreationTechnique).

This is a minor and backwards-compatible edit.

**Comment by baskaufs** [comment]
Note that this does not require public comment or executive approval since it only involves an example.

**Comment by baskaufs** [comment]
Incorporated in [rs.tdwg.org release 2020-10-13](https://github.com/tdwg/rs.tdwg.org/releases/tag/2020-10-13).
