### ISSUE TITLE
Class declarations in RDF rendering

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tdwg/ac#19]
```
In [http://species-id.net/wiki/Audubon_Core_Term_List_RDF_Version | the Term 
List RDF] there are two RDFS Classes defined that are unrelated to the 
[http://species-id.net/wiki/Audubon_Core_Term_List | normative document], which 
has no notion of Class.] Should the normative document take a position on 
whether implementations that do have classes or types use a specific name space?
```

Original issue reported on code.google.com by `morris.bob` on 23 Aug 2012 at 7:27

**Comment by baskaufs** [comment]
OK, I think we can close this one.  The standards doc spec says that basic TDWG vocabularies will just be a bucket of terms with no entailment-generating properties such as range and domain.  People can layer ontologies on top of the basic vocabs if they can show that it serves a purpose.  So the draft RDF representation will go away in favor of the generic machine-readable metadata that will be standard for all TDWG vocabulary terms.

There is a term (tdwgutility:organizedInClass) that DwC (and now AC) uses to categorize terms, but this is only for convenience and there are no entailments from use of this property that imply that the term has a domain of any particular class.
