### ISSUE TITLE
Revise ac:subjectOrientation and ac:subjectPart and add ac:subjectOrientationLiteral and ac:subjectPartLiteral

### ISSUE THREAD

**Issue by baskaufs** [tdwg/ac#195]
# Background

The [Views Task Group](https://github.com/tdwg/ac/tree/master/views) is nearing the completion of its task: creating controlled vocabularies for [ac:subjectPart](http://rs.tdwg.org/ac/terms/subjectPart) and [ac:subjectOrientation](http://rs.tdwg.org/ac/terms/subjectOrientation). In order to implement those vocabularies, we need to adjust the current term metadata for the existing terms to reflect their use with the new vocabularies. In order to follow the pattern established for other Audubon Core properties that are used with controlled values, we need to also mint new term analogs designated specifically for literal controlled value strings: `ac:subjectPartLiteral` and `ac:subjectOrientationLiteral`.  

# Proposal

Here are the specifics of the proposed changes: 

The term definitions are unchanged except to indicate the kind of value intended to be used with them.

All terms are properties. 

No terms are required.

All terms will be considered **not** repeatable. This is a change from the current situation where `ac:subjectPart` and `ac:subjectOrientation` are considered repeatable. See the note below the `ac:subjectOrientation` changes for an explanation. 

## Changes to ac:subjectPart

**Change definition to:** "The portion or product of organism morphology, behaviour, environment, etc. that is either predominantly shown or particularly well exemplified by the media resource, denoted by an IRI."

**Add the following usage notes** "Values SHOULD be selected from the Controlled Vocabulary for Audubon Core subjectPart. In text-based systems such as tables, IRI values MUST be in unabbreviated form."

Delete notes.

## Changes to ac:subjectOrientation

**Change definition to:** "Specific orientation (= direction, view angle) of the subject represented in the media resource with respect to the acquisition device, denoted by an IRI."

**Add the following usage notes** "Values SHOULD be selected from the Controlled Vocabulary for Audubon Core subjectOrientation. In text-based systems such as tables, IRI values MUST be in unabbreviated form."

Delete notes.

*Note: the deleted notes includes the phrase "The term is repeatable e.g., in the case of a composite image, consisting of a combination of different view orientations." This is no longer desirable, since the parts of composite images should ideally be described separately.*

## New term ac:subjectPartLiteral

**Definition:** "The portion or product of organism morphology, behaviour, environment, etc. that is either predominantly shown or particularly well exemplified by the media resource, denoted by a controlled value string."

**Add the following usage notes** "Values SHOULD be selected from the Controlled Vocabulary for Audubon Core subjectPart. It is best practice to use ac:subjectPart instead of ac:subjectPartLiteral whenever practical."

Delete notes.

## New term ac:subjectOrientationLiteral

**Definition:** "Specific orientation (= direction, view angle) of the subject represented in the media resource with respect to the acquisition device, denoted by a controlled value string."

**Add the following usage notes** "Values SHOULD be selected from the Controlled Vocabulary for Audubon Core subjectOrientation. It is best practice to use ac:subjectOrientation instead of ac:subjectOrientationLiteral whenever practical."

Delete notes.

# Implications for stability

The Audubon Core Maintenance Group recognizes that changing the expected value types for `ac:subjectPart` and `ac:subjectOrientation` from literal to IRI may be disruptive for existing implementations. However, after discussion at its [2021-12-15 meeting](https://github.com/tdwg/ac/blob/master/historical/2021-12-15-meeting-notes.pdf), the Maintenance Group felt that the risk of long-term confusion by creating terms that did not follow the "name/nameLiteral" pattern was worse than the short-term disruption caused by requiring data providers to switch from using `ac:subjectPart` and `ac:subjectOrientation` to `ac:subjectPartLiteral` and `ac:subjectOrientationLiteral` for literal values.

**Comment by baskaufs** [comment]
At the 2021-12-15 meeting, the Maintenance Group agreed to move this proposal to public comment.

**Comment by edwbaker** [comment]
Reminder that public comment on this issue closes soon.

**Comment by edwbaker** [comment]
Public comment period has now ended.

**Comment by baskaufs** [comment]
Approved by [Executive Committee decision on 2022-02-23](http://rs.tdwg.org/decisions/decision-2022-02-23_37) and implemented in [this release](https://github.com/tdwg/rs.tdwg.org/releases/tag/2022-02-23)
