### ISSUE TITLE
In RDF use SKOS for Comment and Details fields

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tdwg/ac#20]
```
http://species-id.net/wiki/Audubon_Core_Term_List_RDF_Version should perhaps 
use SKOS instead of rdfs:comment for the Comment and Details fields.


```

Original issue reported on code.google.com by `morris.bob` on 23 Aug 2012 at 7:32

**Comment by baskaufs** [comment]
OK, section 4.5 the Standards Doc Spec says that rdfs:comment is RECOMMENDED for term definitions and dcterms:description MAY be used for supplying additional information.  The spec is silent about applying additional properties.  It also discusses appropriate use of rdfs:label and the SKOS label terms.  So I think all aspects of this issue have been settled by the SDS
