### ISSUE TITLE
Proposal to add terms to define temporal regions of interest within a media item

### ISSUE THREAD

**Issue by baskaufs** [tdwg/ac#208]
This proposal is the result of an extended discussion by the Maintenance Group about developing a system to define and demarcate portions of a media item. For details, see the [meeting notes](https://github.com/tdwg/ac/tree/master/historical). For examples of how to use the new terms, see the [Regions of Interest (ROI) Recipes](https://docs.google.com/document/d/1oTbL_RdtlO288Ixw9vYK7DQgBH6UXfRadvD5s4CER6g/edit?usp=sharing) document.

## Preamble

Temporal regions are specified as an interval with a begin time and an end time. The interval is half-open: the begin time is considered part of the interval whereas the end time is considered to be the first time point that is not part of the interval.

Begin and end times should always be specified in the same format. Begin or end time may each be omitted, with omission implying the value cannot be determined (either because they are un-discernible or because they occur before/after the duration of the source media).

## Proposed terms

**Term name:** ac:startTimestamp
**Type:** rdf:Property
**Label:** Start Timestamp
**Definition:** The beginning of a temporal region, specified as real-world clock time ISO 8601 timestamps, using UTC timezone, with an optional fractional part to indicate milliseconds or finer. There is no limit on the number of decimal places for the decimal fraction. 
**Usage:** This term MAY be applied to a region of interest or an entire media item.

**Term name:** ac:endTimestamp
**Type:** rdf:Property
**Label:** End Timestamp
**Definition:** The end of a temporal region, specified as real-world clock time ISO 8601 timestamps, using UTC timezone, with an optional fractional part to indicate milliseconds or finer. There is no limit on the number of decimal places for the decimal fraction.
**Usage:** This term MAY be applied to a region of interest or an entire media item.

**Term name:** ac:mediaDuration
**Type:** rdf:Property
**Label:** Media Duration
**Definition:** The playback duration of an audio or video file in seconds.
**Notes:** This may be different from the time in seconds calculated as the difference of ac:endTimestamp and ac:startTimestamp if ac:mediaSpeed is not equal to 1.

**Term name:** ac:mediaSpeed
**Type:** rdf:Property
**Label:** Media Speed
**Definition:** The decimal fraction representing the natural speed over the encoded speed.
**Usage:** If a value for ac:mediaSpeed is not provided, applications SHOULD assume that 1.0 is the value.
**Notes:** For example, in a time-lapse recording where 60 seconds of natural time is represented in 1 second of media this would be 60. In a time-expanded recording where 1 second of recording is represented in 5 seconds of media, this would be 0.2.

**Term name:** ac:frameRate
**Type:** rdf:Property
**Label:** Frame Rate
**Definition:** The decimal fraction representing the frequency (rate) at which consecutive images (frames) were captured in real time for a moving image, expressed as the number of frames per second.
**Usage:** This term represents the rate at which consecutive images were captured in real time, not the rate at which the media is encoded to play back the recording. 
**Notes:** For example, in a recording where 60 consecutive images (frames) are captured for each second of the real-time recording, this would be 60. In a time-lapse recording where one image (frame) is recorded every 5 seconds of recording, this would be 0.2.

**Term name:** ac:startTime
**Type:** rdf:Property
**Label:** Start Time in Seconds
**Definition:** The beginning of a temporal region, specified as an absolute offset relative to the beginning of the media item (this corresponds to Normal Play Time RFC 2326), specified as seconds, with an optional fractional part to indicate milliseconds or finer.
**Usage:** This term MUST only be applied to a region of interest.

**Term name:** ac:endTime
**Type:** rdf:Property
**Label:** End Time in Seconds
**Definition:** The end of a temporal region, specified as an absolute offset relative to the beginning of the media item (this corresponds to Normal Play Time RFC 2326), specified as seconds, with an optional fractional part to indicate milliseconds or finer.
**Usage:** This term MUST only be applied to a region of interest.

**Comment by nielsklazenga** [comment]
`ac:framerate` or `ac:frameRate`? I would write 'frame rate' as two words, so I'd prefer the latter.

**Comment by baskaufs** [comment]
A quick google seems to indicate that frame rate is typically two words, so it does seem that `ac:frameRate` would better fit the camelCase conventions we use for properties. Opinion @deepreef?

**Comment by baskaufs** [comment]
Change proposal to implement camelCase suggestion made during review: `ac:frameRate` rather than `ac:framerate`. @deepreef concurred with this change in an email.

**Comment by baskaufs** [comment]
Change proposal to correct incorrect capitalization of rdf:Property

**Comment by baskaufs** [comment]
Ratified by the Executive on 2021-10-05 and implemented in https://github.com/tdwg/rs.tdwg.org/pull/79 and https://github.com/tdwg/ac/pull/212
