### ISSUE TITLE
Cameratrap DP

### ISSUE THREAD

**Issue by vijaybarve** [tdwg/ac#214]
It will be interesting to compare  [Cameratrap DP](https://github.com/tdwg/camtrap-dp) with AC and see what attributes are not covered and do we need tool at adding some of those.

**Comment by baskaufs** [comment]
Pinging @peterdesmet I would love to see coordination between Audubon Core and the Machine Observations Interest Group on this topic.

**Comment by peterdesmet** [comment]
@baskaufs definitely up for that. Maybe good to schedule a call?

**Comment by deepreef** [comment]
I'm interested in this as well!

**Comment by baskaufs** [comment]
I've tagged this as "help wanted". We should change the tag to "Meeting" once one is actually scheduled.

**Comment by baskaufs** [comment]
I'm closing this since we are having the meeting on this topic in a few minutes. We can open more specific issues around this topic as they arise.
