### ISSUE TITLE
Audubon Core Maintenance Group working session

### ISSUE THREAD

**Issue by baskaufs** [tdwg/ac#215]
The Audubon Core Maintenance Group will be holding an online working session associated with the TDWG Annual Meeting. It will take place from 21:00 to 22:00 UTC on Wednesday, 10 November. 

At the session, we'll provide a general overview of what Audubon Core is and how it is maintained. We will recount the key accomplishments of the past year, and review open issues in the tracker. There will also be an opportunity to discuss future directions for the group. 

To register for the event, view the entire schedule, and see time zone information, view [this news item](https://www.tdwg.org/conferences/2021/working-sessions/).

**Comment by baskaufs** [comment]
The notes from the Audubon Core Maintenance Group working session have been posted at https://github.com/tdwg/ac/blob/master/historical/2021-11-10-working-session-notes.pdf 

The AC MG annual report is also available at https://github.com/tdwg/ac/blob/master/historical/ac-2021-annual-report.md

**Comment by danstowell** [comment]
Let's also log here the video recording, when it becomes available. I think your intro was a very good overview, so I'd like to share it. (I propose reopening this issue and closing it when we have the video link)

**Comment by danstowell** [comment]
The **video** of the AC MG working session is here (1 hour): https://www.youtube.com/watch?v=K-UCGyVz3mY
