### ISSUE TITLE
ac:framerate in ROI vocabulary

### ISSUE THREAD

**Issue by edwbaker** [tdwg/ac#217]
Currently `ac:framerate` is organized in the Region of Interest Vocabulary section of the [Term List document](https://ac.tdwg.org/termlist/). This proposal is to move it to the Resource Creation Vocabulary (to be with its audio analog `mo:sample_rate`). 

Existing metadata:
```
ac:framerate tdwgutility:organizedInClass <http://rs.tdwg.org/ac/terms/RegionOfInterest>.
```

Proposed metadata:
```
ac:framerate tdwgutility:organizedInClass <http://rs.tdwg.org/dwc/terms/attributes/ResourceCreation>.
```

# Implications

This is an organizational change that has no effect on implementations.

**Comment by baskaufs** [comment]
On 2021-12-05, the Maintenance Group agreed to move this to public comment.

**Comment by edwbaker** [comment]
Reminder that public comment on this issue closes soon.

**Comment by edwbaker** [comment]
Public comment period has now ended.

**Comment by baskaufs** [comment]
Approved by [Executive Committee decision on 2022-02-23](http://rs.tdwg.org/decisions/decision-2022-02-23_38) and implemented in [this release](https://github.com/tdwg/rs.tdwg.org/releases/tag/2022-02-23)
