### ISSUE TITLE
Replace notes in subtype CV metadata with sawsdlrdf:modelReference links

### ISSUE THREAD

**Issue by baskaufs** [tdwg/ac#220]
Currently, most of the terms in the [subtype controlled vocabulary](http://rs.tdwg.org/ac/doc/subtype/) include a value for "Notes" that reference a concept in the [Getty Arts and Architecture (AAT) Thesaurus](http://www.getty.edu/research/tools/vocabularies/aat/). This proposal would convert those notes into actual semantic links using the property `sawsdlrdf:modelReference` (<http://www.w3.org/ns/sawsdl#modelReference>).

The property `sawsdlrdf:modelReference` links to a concept in a semantic model and is intended to provide semantic information about the resource being annotated. It was created for annotating XML components, but nothing in its semantics prevents it from being used with other resources. It does not have any domain or range, so using it does not create any entailments related to the subject or object resources. See [this](https://www.w3.org/TR/sawsdl/#modelReference) and [this](https://www.w3.org/TR/sawsdl/#rdfmapping) for more information. 

Example change: `acsubtype:Animation` (<http://rs.tdwg.org/acsubtype/values/Animation>)

**Human readable:**
- Delete notes "~See http://vocab.getty.edu/page/aat/300411663~"
- Add a new field "Refer to semantic model:" with value "http://vocab.getty.edu/page/aat/300411663"

**Machine readable:**
- Delete the triple: `acsubtype:Animation dcterms:description "See http://vocab.getty.edu/page/aat/300411663"@en.`
- Add the triple: `acsubtype:Animation sawsdlrdf:modelReference <http://vocab.getty.edu/page/aat/300411663>.`

This change would apply to all terms in the Controlled Vocabulary for Audubon Core subtype that have notes fields referring to AAT concepts. The note for acsubtype:Film would be changed to simply "Also known as motion pictures."

# TDWG-wide implications

In several contexts, there has been discussion of how to semantically link TDWG-minted terms to definitions outside TDWG when the TDWG and non-TDWG terms are of different types. In this case, the TDWG terms are `rdfs:Class` and the AAT terms are `skos:Concept`. Two Darwin Core proposals ([here](https://github.com/tdwg/dwc/issues/40#issuecomment-824495721) and [here](https://github.com/tdwg/dwc/issues/38#issuecomment-824504512)) suggested linking controlled values (`skos:Concepts`) to ENVO classes. 

[Section 4.1.2 of the TDWG Standards Documentation Specification](https://github.com/tdwg/vocab/blob/master/sds/documentation-specification.md#41-identifying-a-resource-and-the-machine-readable-document-that-describes-it) provides guidance about the how TDWG terms should be typed and thus far, a clear distinction has been maintained between classes, properties, and controlled value concepts. 

It has been suggested that [SKOS mapping relations](https://www.w3.org/TR/skos-primer/#secmapping) such as `skos:exactMatch` and `skos:closeMatch` be used to link TDWG terms to terms outside TDWG. However, the [range and domain properties of these mapping relations terms](https://www.w3.org/TR/skos-reference/) entail that the terms being linked are both `skos:Concept`. Thus using the mapping relation terms would result in terms that were defined to be both properties and concepts, or as both classes and concepts. Although SKOS was designed to allow for exploration of design patterns that involved creating models that are both concept schemes and ontologies, using the SKOS mapping relations to link any combination of terms other than two concepts blurs the distinction between term types that has been maintained so far within TDWG. 

Linking with `sawsdlrdf:modelReference` is an alternative to using the SKOS mapping relations that maintains the distinction between term types. Although less well-known than the SKOS relations, it is defined by a W3C Recommendation. There is previous precedent in TDWG vocabularies for using terms that are not well known for utilitarian purposes. For example, `tdwgutility:abcdEquivalence` is used in Darwin Core to map Darwin Core terms to ABCD elements and `tdwgutility:organizedInClass` is used in both Audubon and Darwin Cores to categorize terms. 

If this proposal is adopted and a precedent is set, `sawsdlrdf:modelReference` would be used in the proposed controlled vocabularies for subjectPart and subjectOrientation being developed by the [Audubon Core Views task group](https://github.com/tdwg/ac/tree/master/views). It is already in place in the draft vocabularies (see [this](https://tdwg.github.io/rs.tdwg.org/cvJson/acpart.json) and [this](https://tdwg.github.io/rs.tdwg.org/cvJson/acorient.json) for usage). We would also expect that the same pattern would be used if the two Darwin Core proposals mentioned above were moved forward.

**Comment by baskaufs** [comment]
Some links related to mappings:
https://github.com/mapping-commons/sssom/issues/40
https://github.com/mapping-commons/sssom/issues/43

**Comment by baskaufs** [comment]
At the 2021-12-15 meeting, the Maintenance Group agreed to move this to public comment.

**Comment by edwbaker** [comment]
Reminder that public comment on this issue closes soon.

**Comment by baskaufs** [comment]
Approved by [Executive Committee decision on 2022-02-23](http://rs.tdwg.org/decisions/decision-2022-02-23_36) and implemented in [this release](https://github.com/tdwg/rs.tdwg.org/releases/tag/2022-02-23)
