### ISSUE TITLE
Audubon Core Maintenance Group call 20:00 UTC, Wednesday, 2 February 2022

### ISSUE THREAD

**Issue by baskaufs** [tdwg/ac#224]
The Audubon Core Maintenance Group will have an online meeting at 20:00 UTC Wednesday, 2022-02-02. That corresponds to 3:00 PM Wednesday eastern (US) standard time (New York), 2:00 PM Wednesday central (US) standard time (Chicago), 10:00 AM Wednesday Hawaii standard time (Honolulu), 7:00 AM Thursday Australian eastern daylight time (Canberra), 8:00 PM Wednesday GMT (London), and 9:00 PM Wednesday central European time (Brussels).

We will discuss priorities for Audubon Core in 2022. 

Meeting details:

Join Zoom meeting:
https://vanderbilt.zoom.us/j/93242348096

Find your local number: https://vanderbilt.zoom.us/u/abVZNA3Iqu

**Comment by edwbaker** [comment]
Meeting notes available at https://github.com/tdwg/ac/blob/master/historical/2022-02-02-meeting-notes.pdf
