### ISSUE TITLE
http://ns.adobe.com/xap/1.0/ doesn't resolve

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/ac#228]
AC adopts 6 terms from [Adobe XMP Core Properties](https://wwwimages2.adobe.com/content/dam/acom/en/devnet/xmp/pdfs/XMP%20SDK%20Release%20cc-2016-08/XMPSpecificationPart1.pdf). It seems that `http://ns.adobe.com/xap/1.0/` (e.g. http://ns.adobe.com/xap/1.0/MetadataDate) doesn't resolve. Is that an issue for machine or humans? Is it something we should notify Adobe about?

**Comment by edwbaker** [comment]
Looking at Wayback Machine it looks like this hasn't been resolvable since January 2017: https://web.archive.org/web/2017*/http://ns.adobe.com/xap/1.0/ .

@baskaufs - is this something that has been discussed previously?

**Comment by baskaufs** [comment]
Many of the terms in AC borrowed namespaces never dereferenced. This was known at the time of adoption, so I don't think we need to worry about it. See the [notes in Section 2 of the term list document](https://ac.tdwg.org/termlist/#2-borrowed-vocabulary) for more on this. I'm pretty confident Adobe doesn't care and probably never has.

**Comment by baskaufs** [comment]
I'm going to just close this since I don't think there is anything to do about it.
