### ISSUE TITLE
GitHub repo website

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/ac#232]
The URL included in the repository description is:

<img width="329" alt="Screenshot 2022-02-11 at 11 06 09" src="https://user-images.githubusercontent.com/600993/153572816-0ba41dea-c69e-429b-a5a1-51e756ef0708.png">

That is indeed the official URL for the standard, but it points to itself (the repo): http://www.tdwg.org/standards/638

I would suggest to make a bit more user friendly and point to https://ac.tdwg.org/

**Comment by baskaufs** [comment]
Cool. When I get some time, I can try to update and make a pull request.

**Comment by MattBlissett** [comment]
I've deployed the redirect configuration, thanks Steve.
