### ISSUE TITLE
Outdated Link in Notes for Iptc4xmpExt:CVterm

### ISSUE THREAD

**Issue by DavidFichtmueller** [tdwg/ac#244]
In the notes section for [Iptc4xmpExt:CVterm](https://ac.tdwg.org/termlist/#Iptc4xmpExt_CVterm) it says: 

> "Recommended sets include: [...], Subject Categories defined in Key to Nature (K2N; http://www.keytonature.eu/wiki/Subject_Category),"

The problem is that the KeyToNature domain, which previously had pointed to the Biowikifarm where the linked site was hosted, has been sold and now points to a web shop for herbal supplements. I don't know about the state of the project in general. 

In case this is of any help, here is an export of the linked page, before it became not accessible anymore:
[Subject Category - KeyToNature.pdf](https://github.com/tdwg/ac/files/9559052/Subject.Category.-.KeyToNature.pdf)

I decided to create a new issue for this and not post in #230, as the problems discussed there are more of a general nature and this is a documentation fix on a non-normative property of the term.

**Comment by baskaufs** [comment]
Thanks for catching this @DavidFichtmueller. Maybe we can post the PDF in GitHub and then link to it the next time we do an update of the list of terms.

**Comment by MattBlissett** [comment]
The Wayback Machine also has an archive: https://web.archive.org/web/20181026124324/http://www.keytonature.eu/wiki/Subject_Category

**Comment by baskaufs** [comment]
This issue is handled by #246, which is going to public comment now
