### ISSUE TITLE
Investigate GUANO audio metadata standard

### ISSUE THREAD

**Issue by edwbaker** [tdwg/ac#247]
Would be good to get a specification and perform a crosswalk

**Comment by danstowell** [comment]
The format is documented here https://github.com/riggsd/guano-spec/blob/master/guano_specification.md

**Comment by danstowell** [comment]
It's all broadly compatible - very easy to map onto AC and DwC, and we might consider whether some of their terms might be adopted (e.g. their "Filter HP" and "Filter LP" seem useful).

Their "time-expansion (TE)" field is somewhat related to `ac:mediaSpeed`: one is the reciprocal of the other, though note that their TE is constrained to integer values.

**Comment by danstowell** [comment]
Notes from 2024-02-20 working session:

* We intend to incorporate "Filter HP" and "Filter LP" into avcore, and will take this forward. See #264
* The relation to time-expansion is already documented in the term notes
