### ISSUE TITLE
Do the renaming to "Audio-visual Core" in github, website etc

### ISSUE THREAD

**Issue by danstowell** [tdwg/ac#249]
The renaming to "Audio-visual Core" was discussed publicly, and confirmed in recent maintenance group meetings. Aside from any external issues such as wider TDWG documents, can we make a start by changing the text in the Github, our main website, etc?

I'll make some edits in the wiki page, readme, github metadata, though there may be plenty of changes missed.

I believe the agreed hyphenation and capitalisation is "Audio-visual Core", but please correct me if I'm wrong.

**Comment by baskaufs** [comment]
I don't remember what was concluded about the hyphen, but it seems to me that "audiovisual" is more common than "audio-visual". Therefore, it seems likely to introduce fewer typing errors if we used "Audiovisual Core". We would still be able to use the nickname "AV Core" and pronounce it "aw vee" (or "ay vee") if we wanted since "AV" is a typical abbreviation for audiovisual. Other Maintenance Group members: please weigh in on this since I don't remember what our conclusion was.

**Comment by edwbaker** [comment]
I think audiovisual is slightly neater although audio-visual is what is in
the OED.

Do we need to spell it out or could be just go with AV Core?

**Comment by danstowell** [comment]
IMHO "Audiovisual Core" (with no hyphen) is a good choice. I would prefer it to be the full word rather than just "AV", though I wouldn't be surprised if people refer to it informally as "AVCore" or similar in future.

... However, I'd prefer something as big as a name change to be handled properly, i.e. through the whole maintenance group. My apologies for tweaking the readme already; I copied and pasted the term from the last set of minutes, assuming it was settled.

**Comment by baskaufs** [comment]
My understanding was that the MG had agreed to do it (see https://github.com/tdwg/ac/blob/master/historical/2022-10-28-meeting-notes.pdf). I think one of the holdups was that someone was going to write up an explanation for why we were making the change, which I don't think has happened yet.

**Comment by vijaybarve** [comment]
Audiovisual Core sounds good to me.

**Comment by Cycloderes** [comment]
Sorry for the intrusion, but as a follower of this working group and as a user adopting the standard in our Museum, Audiovisual Core also sounds good to me.

**Comment by edwbaker** [comment]
Seems that audiovisual with no hyphen has the widest support.

**Comment by baskaufs** [comment]
I believe this has all been completed.
