### ISSUE TITLE
rs.tdwg.org/ac redirection issue for `variant/2020-10-13`

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/ac#255]
On [this page](https://ac.tdwg.org/variant/) the following URL is mentioned

> Previous version: http://rs.tdwg.org/ac/doc/variant/2020-10-13

It redirects to https://ac.tdwg.org/ac/variant/2020-10-13 (error) rather than https://ac.tdwg.org/variant/2020-10-13 (correct)

The `Previous version` and `Replaced by` links work for all other pages (I checked)

**Comment by baskaufs** [comment]
Fixed in https://github.com/tdwg/rs.tdwg.org/commit/f021d32f43dc28d6431c85498aa490c1e3183d52

**Comment by baskaufs** [comment]
Good catch @peterdesmet
