### ISSUE TITLE
Term change: correct reference to `ac:accessURI` in `ac:serviceExpectation`

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/ac#260]
### Submitter

@peterdesmet

### Efficacy Justification (why is this change necessary?)

Fixing an incorrect reference to `ac:accessURL` in `ac:serviceExpectation`. There is no `ac:accessURL`, I think the intended term is [`ac:accessURI`](https://ac.tdwg.org/termlist/#ac_accessURI) (URI, not URL)

### Demand Justification (if the change is semantic in nature, name at least two organizations that independently need this term)

n/a

### Stability Justification (what concerns are there that this might affect existing implementations?)

n/a

### Current Term definition

https://ac.tdwg.org/termlist/#ac_serviceExpectation

## Term change

Proposed attributes of the new term version (Please put actual changes to be implemented in **bold** and ~strikethrough~):

### Definition of the term (normative)

> A term that describes what service expectations users may have of the ~ac:accessURL~ **ac:accessURI**.

**Comment by baskaufs** [comment]
Fixed in https://github.com/tdwg/rs.tdwg.org/releases/tag/2023-09-05 and https://github.com/tdwg/ac/pull/262

**Comment by edwbaker** [comment]
@baskaufs to follow up following Working Session.

**Comment by baskaufs** [comment]
It was fixed, so closing
