### ISSUE TITLE
Typo in dc:format

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/ac#261]
### Submitter

@peterdesmet

### Efficacy Justification (why is this change necessary?)

Correcting a type (the the)

### Demand Justification (if the change is semantic in nature, name at least two organizations that independently need this term)

n/a

### Stability Justification (what concerns are there that this might affect existing implementations?)

n/a

### Current Term definition

https://ac.tdwg.org/termlist/#dc_format

## Term change

Proposed attributes of the new term version (Please put actual changes to be implemented in **bold** and ~strikethrough~):

### Usage

Second sentence in

> A controlled value string describing the technical format of the resource (file format or physical medium). The string SHOULD be a controlled value from the ~the~ Audiovisual Core Controlled Vocabulary for Dublin Core format, although it MAY be any Media Type (MIME type) value from the IANA list of Media Types (https://www.iana.org/assignments/media-types/media-types.xhtml) or any commonly used file extension string. Human-readable information about the Controlled Vocabulary for format is at http://rs.tdwg.org/ac/doc/format/ .

**Comment by baskaufs** [comment]
Fixed in https://github.com/tdwg/rs.tdwg.org/releases/tag/2023-09-05 and https://github.com/tdwg/ac/pull/262
