### ISSUE TITLE
reference to Audubon Core in links on AC page

### ISSUE THREAD

**Issue by gkampmeier** [tdwg/ac#263]
The home page [https://www.tdwg.org/standards/ac/](https://www.tdwg.org/standards/ac/) for Audiovisual Core has links to content under Parts of the Standard that reference "Audubon Core" rather than rebranded "Audiovisual Core": 

- Audiovisual Core main vocabulary [http://rs.tdwg.org/ac.htm](http://rs.tdwg.org/ac.htm)
- variant controlled vocabulary [http://rs.tdwg.org/acvariant/](http://rs.tdwg.org/acvariant/)
- format controlled vocabulary [http://rs.tdwg.org/format/](http://rs.tdwg.org/format/) 
- subtype controlled vocabulary [http://rs.tdwg.org/acsubtype/](http://rs.tdwg.org/acsubtype/)

**Comment by baskaufs** [comment]
@gkampmeier It took me [three tries](https://github.com/tdwg/rs.tdwg.org/releases) but I think (hope?) I have caught all of the instances of "Audubon".
