### ISSUE TITLE
Provide examples illustrating how to use AC terms in various circumstances

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tdwg/ac#63]
```
1. Provide an ac Term Name or Label. no particular term
2. Describe the defect or lack of clarity you find in the term. 

At a number of points in the public comment, questions were asked which didn't 
necessarily require changes to terms or additions of missing terms, but rather 
required clarification of how to use the existing terms.  This could probably 
be done most easily by providing some examples.  However, since AC is 
representation-independent, it would probably be best to include examples as 
part of best-practices guides for various kinds of representations (simple 
text, XML, RDF, etc.).  Given that such guides are not likely to be completed 
before the ratification of the generic standard, would it be beneficial to have 
some document (perhaps on the wiki) giving some simple examples to make the use 
of the terms more clear?
```

Original issue reported on code.google.com by `steve.ba...@vanderbilt.edu` on 9 Apr 2013 at 1:20

**Comment by baskaufs** [comment]
Comment copied from  https://github.com/tdwg/ac/issues/117:

> Find out how GBIF, iDigBio, SYMBIOTA etc. are, or would like to, be using Audubon Core and create best practice document based on that.

**Comment by baskaufs** [comment]
Comment copied from https://github.com/tdwg/ac/issues/117:

> An example of use is the NEVP project, wrapping DwC and AC assertions about information captured at a high throughput digitization apparatus in a W3C Annotation document for transport to Symbiota and the database of record for ingest of that data. For an example document see: https://sourceforge.net/p/filteredpush/svn/HEAD/tree/FP-Design/trunk/ontologies/oadExamples/NEVP_specimen_example.xml There is also code in Symbiota to process these documents. @ramorrismorris was involved in crafting these documents.

**Comment by baskaufs** [comment]
We now have an examples guide for Still Images: https://github.com/tdwg/ac/blob/master/image/examples.md
and a stub for Sound: https://github.com/tdwg/ac/blob/master/sound/examples.md
We have established this paradigm and can generate guides for other media types when there is interest to create them.
