### ISSUE TITLE
Examine AC terms for minor internal mis-placements of attributes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tdwg/ac#90]
```
Examine AC term list to see if has similar minor issue as Darwin Core, 
described at https://github.com/tdwg/dwc/issues/26  which says in part "The 
gist [...] is that recommendations on how to populate a term are often in the 
definition whereas we would like them to be consistently in the comments 
section. 

If yes, prepare a list of the affected terms


```

Original issue reported on code.google.com by `morris.bob` on 19 Jan 2015 at 5:03

**Comment by baskaufs** [comment]
See the thread of issue #109 for an explanation of why this has been closed.  There may still be some misplacement of normative and non-normative content in term Definition, Usage, and Notes fields, but it will take a concerted group effort to work that out.
