### ISSUE TITLE
Document rewrite rules needed for rs.tdwg.org

### ISSUE THREAD

**Issue by mdoering** [tdwg/ac#92]
Does AC need to have any redirects (see tdwg/infrastructure#59) from rs.tdwg.org or any other tdwg domain?

**Comment by ramorrismorris** [comment]
The mrtg directory has an ancient memorislization of an experimental rdf draft of ac before its current namespace. It carries a clear warning that it is not appropriate as a representation of Audubon Core. Even for historical interest it contains little or nothing that an archeologist cannot get from the wiki. My suggestion is to throw it out.  Gabi, Steve, and Gregor might have a position.

**Comment by baskaufs** [comment]
Presumably earlier drafts are preserved as part of the record of the review process. If the others concur it seems like it should go away. Steve

**Comment by csparr** [comment]
There has been no action on this and it sounds like nobody cares about rewrites, so I am closing it.  Reopen if necessary. the rs.tdwg.org service is going down ASAP.

**Comment by baskaufs** [comment]
Do you mean that ALL rewrites from rs.tdwg.org are going to stop?  If so, that's terrible - it would break dereferencing of all of the Darwin Core terms.  If it's only the rewrites from Audubon Core, then I don't suppose anybody cares.

**Comment by mdoering** [comment]
Steve, we are migrating the redirects and rs.tdwg.org will certainly continue to exist. We just need to be sure that the content actually exists on a different server. DwC is served by github.io these days, tapir too and AC seems to be backed by the terms.tdwg.org wiki: https://github.com/tdwg/infrastructure/blob/master/vhosts/rs.tdwg.org.conf#L97

Please see #59 for details

**Comment by baskaufs** [comment]
Oh, OK.  Sorry, I was just misunderstanding what Cyndy meant when she said the service was going down.
