### ISSUE TITLE
check human-readable documents for compliance with the Standards Documentation Specification

### ISSUE THREAD

**Issue by baskaufs** [tdwg/ac#93]
We should check the various human-readable documents for conformance to the Standards Documentation Specification, particularly section 3 about human-readable documents.[1]  

[1] https://github.com/tdwg/vocab/blob/master/sds/documentation-specification.md#3-human-readable-documents

**Comment by ramorrismorris** [comment]
Consider
   3.1.4  Abstract
   An abstract MUST provide a brief description of the purpose of the standard

If something elsewhere requires that there be  an abstract, this text should say
   _The_ abstract ...
Otherwise, this text should be something like
    _If there is an abstract it MUST provide_ ...

**Comment by ramorrismorris** [comment]
3.2 Descriptive documents has a similar problem to my comment about 3.1.4.

**Comment by baskaufs** [comment]
Hmmm.  The lack of clarity Bob notes probably isn't easily fixable at this point since it resides in the documentation specification as ratified.  I think the meaning intended was that there must be an abstract and it must provide a brief description.  

I've made a first pass at bringing the four major AC documents into conformance with the SDS.  They are currently at https://github.com/tdwg/ac/tree/documentation-conversion/doc .  I think that the remaining issues with those documents are related to clarity rather than conformance, so I'm going to go ahead and close this since we will continue to look at and discuss the status of those docs at our next Maintenance Group hangout.
