### ISSUE TITLE
Examine the DICOM standard for useful pieces

### ISSUE THREAD

**Issue by baskaufs** [tdwg/ac#95]
See https://en.wikipedia.org/wiki/DICOM

Since it's used with 3D radiological images, there may be pieces that could be borrowed for an AC extension on 3D media.

**Comment by ramorrismorris** [comment]
See also https://www.floridamuseum.ufl.edu/science/new-project-allows-users-to-explore-3d-specimens/

**Comment by baskaufs** [comment]
The DICOM standard has been reviewed by the 3D Task Group and its terms have been under consideration. So this issue does not need to stay open.
