### ISSUE TITLE
strengthening the rigor of dc:format to enable research use

### ISSUE THREAD

**Issue by danstoner** [tdwg/ac#98]
In an aggregated data setting, the lack of technical metadata about the Format of the resource limits the utility of published media for discovery, analysis, and re-use.

Examples of activities that are not reasonably possible without the media format specified in the metadata:

1. search for DNG images
2. search for sounds
3. search for 3D-printable objects

In particular, I believe that strengthening the rigor and requirement of dc:format would help.

https://terms.tdwg.org/wiki/Audubon_Core_Term_List#dc:format

I observe that the current Notes section of dc:format seems be internally conflicted between best practice and recommended values:

> Recommended best practice is to use a controlled vocabulary such as the list of Internet Media Types [MIME].

vs.

> Three types of values are recommended: (a) any MIME type; (b) common file extensions like txt, doc, odf, jpg/jpeg, png, pdf; (c) the following special values: Data-CD, Audio-CD, Video-CD, Data-DVD, Audio-DVD, Video-DVD-PAL, Video-DVD-NTSC, photographic slide, photographic print. Compare Type for the content-type.

@ramorrismorris says: I concur that two different things are in the Notes. At a glance, dc:format and dcterms:format have neither and arguably we should follow that. There should be a separate place for a library of examples. One in such a library might be the completed iDigBio one proposed by @danstoner .  Probably doing this should be be warned here in another issue. #99 

I will add that there are no instances in iDigBio (23+ million media) where the provider included a "format" field using the special values from "c" above.  Every instance is either an actual IANA media type, an attempt at specifying a MIME type, or a "commonly used file extension" for the media as stored on a local filesystem.

These are the media Format values seen "in the wild":

```
$ http 'http://search.idigbio.org/v2/summary/top/media?top_fields=format&mq={"format":{"type":"exists"}}&count=1000'
HTTP/1.1 200 OK
Cache-Control: public, max-age=300
Content-Length: 1675
Content-Type: application/json; charset=utf-8
Date: Mon, 30 Apr 2018 13:34:05 GMT
Last-Modified: Tue, 24 Apr 2018 09:13:02 GMT
Vary: Accept-Encoding, Origin
```
```JSON
{
    "format": {
        "adoberawdng": {
            "itemCount": 1
        }, 
        "application": {
            "itemCount": 739
        }, 
        "application/pdf": {
            "itemCount": 3757
        }, 
        "application/ply": {
            "itemCount": 3
        }, 
        "application/stl": {
            "itemCount": 253
        }, 
        "application/vnd.ms-excel": {
            "itemCount": 21
        }, 
        "application/x-unknown": {
            "itemCount": 2
        }, 
        "application/xml": {
            "itemCount": 439
        }, 
        "application/zip": {
            "itemCount": 1
        }, 
        "audio/mpeg": {
            "itemCount": 7
        }, 
        "audio/mpeg3": {
            "itemCount": 2325
        }, 
        "audio/wav": {
            "itemCount": 14
        }, 
        "audio/x-wav": {
            "itemCount": 14
        }, 
        "bmp": {
            "itemCount": 3
        }, 
        "dc:format": {
            "itemCount": 1
        }, 
        "gif": {
            "itemCount": 310
        }, 
        "html": {
            "itemCount": 3
        }, 
        "image/bmp": {
            "itemCount": 348
        }, 
        "image/dng": {
            "itemCount": 223390
        }, 
        "image/jp2": {
            "itemCount": 24654
        }, 
        "image/jpeg": {
            "itemCount": 21030454
        }, 
        "image/jpg": {
            "itemCount": 1458
        }, 
        "image/pcd": {
            "itemCount": 4
        }, 
        "image/png": {
            "itemCount": 228
        }, 
        "image/tiff": {
            "itemCount": 233366
        }, 
        "image/x-adobe-dng": {
            "itemCount": 177754
        }, 
        "image/x-photo-cd": {
            "itemCount": 9
        }, 
        "jpeg": {
            "itemCount": 692078
        }, 
        "jpg": {
            "itemCount": 1224847
        }, 
        "model/vrml": {
            "itemCount": 221
        }, 
        "mp4": {
            "itemCount": 17
        }, 
        "mpeg": {
            "itemCount": 11
        }, 
        "msword": {
            "itemCount": 12
        }, 
        "pdf": {
            "itemCount": 2
        }, 
        "plain": {
            "itemCount": 7
        }, 
        "png": {
            "itemCount": 62
        }, 
        "quicktime": {
            "itemCount": 22
        }, 
        "text/html": {
            "itemCount": 65633
        }, 
        "text/plain": {
            "itemCount": 2
        }, 
        "tiff": {
            "itemCount": 5
        }, 
        "video/avi": {
            "itemCount": 1
        }, 
        "video/mp4": {
            "itemCount": 17
        }, 
        "video/quicktime": {
            "itemCount": 1
        }, 
        "vnd.ms-excel": {
            "itemCount": 5
        }, 
        "vnd.ms-pki.stl": {
            "itemCount": 12
        }, 
        "vnd.openxmlformats-officedocument.spreadsheetml.sheet": {
            "itemCount": 1
        }, 
        "vnd.openxmlformats-officedocument.wordprocessingml": {
            "itemCount": 1
        }, 
        "vnd.openxmlformats-officedocument.wordprocessingml.document": {
            "itemCount": 5
        }, 
        "x-bmp": {
            "itemCount": 2
        }, 
        "x-unknown": {
            "itemCount": 10
        }
    }, 
    "itemCount": 23682532
}

```

Going forward it would also be helpful to deal with the case when a media type is not available in the standard IANA media types.  For example, some of the popular 3D imaging formats are not in the IANA standard media types:

https://www.iana.org/assignments/media-types/media-types.xhtml

**Comment by baskaufs** [comment]
This issue has been addressed in the proposal for a controlled vocabulary for dc:/dcterms:format https://github.com/tdwg/ac/issues/171
